import LargeModelsIntroduction from "../../../docs/markdown/大模型是如何工作的/00-章节导读.md";
import WhatAreLargeModels from "../../../docs/markdown/大模型是如何工作的/01-什么是大模型.md";
import TokensAndVectors from "../../../docs/markdown/大模型是如何工作的/02-文字怎样变成Token与向量.md";
import AttentionAndTransformer from "../../../docs/markdown/大模型是如何工作的/03-注意力与Transformer.md";
import NextTokenPrediction from "../../../docs/markdown/大模型是如何工作的/04-预测下一个Token.md";
import FromBaseModelToAssistant from "../../../docs/markdown/大模型是如何工作的/05-从基础模型到AI助手.md";
import MultimodalGeneration from "../../../docs/markdown/大模型是如何工作的/06-图片视频与多模态生成.md";
import AgentsWorldModelsAndEmbodiedAi from "../../../docs/markdown/大模型是如何工作的/07-Agent世界模型与具身智能.md";
import HallucinationBiasAndSafety from "../../../docs/markdown/大模型是如何工作的/08-幻觉偏差资源与安全边界.md";
import LargeModelChallenges from "../../../docs/markdown/大模型是如何工作的/09-动手实验与章节挑战.md";
import LargeModelGlossary from "../../../docs/markdown/大模型是如何工作的/10-术语表与参考资料.md";
import { markdownSections, type LessonEntry } from "./course-types";

const common = {
  chapter: "large-models",
  contentKind: "markdown" as const,
  audience: "建议年龄 10—14 岁",
};

export const largeModelLessons: LessonEntry[] = [
  {
    ...common,
    slug: "introduction",
    chapterLabel: "大模型如何工作 · 章节导读",
    title: "大模型是如何工作的：章节导读",
    description: "从大模型生成文字、图片和行动的现象出发，建立从表示、训练到安全边界的完整学习路线。",
    readingTime: "预计学习 10—12 分钟",
    sections: markdownSections(
      "这一章从一个误会开始",
      "适合谁学习",
      "学习路线",
      "学完后的能力目标",
      "本章的三条边界",
      "原始资料说明",
    ),
    Content: LargeModelsIntroduction,
  },
  {
    ...common,
    slug: "what-are-large-models",
    chapterLabel: "大模型如何工作 · 第 1 课",
    title: "什么是大模型",
    description: "理解参数、模型规模、数据和计算之间的关系，认识稠密模型与混合专家模型。",
    readingTime: "预计学习 35—40 分钟",
    sections: markdownSections(
      "本课目标",
      "大模型没有跳出神经网络",
      "大语言模型只是大模型家族的一员",
      "参数到底是什么",
      "稠密模型与混合专家模型",
      "更大为什么可能更强",
      "参数、数据和计算必须配合",
      "算力、能源与水怎样进入讨论",
      "检查理解",
      "本课小结",
      "参考资料",
    ),
    Content: WhatAreLargeModels,
  },
  {
    ...common,
    slug: "tokens-and-vectors",
    chapterLabel: "大模型如何工作 · 第 2 课",
    title: "文字怎样变成 Token 与向量",
    description: "跟随文字进入模型的过程，理解 Token、编号、嵌入向量与位置信息的作用。",
    readingTime: "预计学习 20—25 分钟",
    sections: markdownSections(
      "本课目标",
      "模型不能直接“读”汉字",
      "Token 是什么",
      "规范化与预分词",
      "Token ID 只是查表地址",
      "嵌入向量把离散符号变成可学习表示",
      "为什么要加入位置信息",
      "Token 化会带来哪些实际影响",
      "小活动：设计一个分词器",
      "本课小结",
      "参考资料",
    ),
    Content: TokensAndVectors,
  },
  {
    ...common,
    slug: "attention-and-transformer",
    chapterLabel: "大模型如何工作 · 第 3 课",
    title: "注意力与 Transformer",
    description: "理解自注意力、Query、Key、Value、多头注意力和 Transformer 层怎样连接上下文信息。",
    readingTime: "预计学习 18—22 分钟",
    sections: markdownSections(
      "本课目标",
      "为什么顺序处理不够",
      "自注意力在问什么",
      "Query、Key 和 Value",
      "为什么要多头注意力",
      "一层 Transformer 还包含什么",
      "编码器、解码器和仅解码器模型",
      "标准注意力的代价",
      "注意力权重不等于完整解释",
      "检查理解",
      "本课小结",
      "参考资料",
    ),
    Content: AttentionAndTransformer,
  },
  {
    ...common,
    slug: "next-token-prediction",
    chapterLabel: "大模型如何工作 · 第 4 课",
    title: "预测下一个 Token",
    description: "观察自回归生成循环、训练并行与采样方式，理解长回答怎样由连续预测逐步形成。",
    readingTime: "预计学习 20—25 分钟",
    sections: markdownSections(
      "本课目标",
      "核心任务听起来像文字接龙",
      "自回归生成的循环",
      "训练时为什么能并行",
      "为什么相同问题可能得到不同答案",
      "只预测下一步，为什么能回答问题",
      "上下文窗口不是永久记忆",
      "一步错误为什么会扩散",
      "小活动：你来预测下一个 Token",
      "本课小结",
      "参考资料",
    ),
    Content: NextTokenPrediction,
  },
  {
    ...common,
    slug: "from-base-model-to-assistant",
    chapterLabel: "大模型如何工作 · 第 5 课",
    title: "从基础模型到 AI 助手",
    description: "区分预训练、指令微调、偏好对齐、检索和产品系统，理解会续写为何不等于会帮助人。",
    readingTime: "预计学习 20—25 分钟",
    sections: markdownSections(
      "本课目标",
      "原始基础模型只关心“合理后文”",
      "从基础模型到助手的几个阶段",
      "模型、提示词、检索和微调有什么区别",
      "“聊天产品”由多个系统组成",
      "对齐的难点",
      "小练习：选择正确的改进方法",
      "本课小结",
      "参考资料",
    ),
    Content: FromBaseModelToAssistant,
  },
  {
    ...common,
    slug: "multimodal-generation",
    chapterLabel: "大模型如何工作 · 第 6 课",
    title: "图片、视频与多模态生成",
    description: "认识扩散、潜在空间、文字条件与多模态连接，理解图片和视频生成的基本路径与核验方法。",
    readingTime: "预计学习 24—30 分钟",
    sections: markdownSections(
      "本课目标",
      "图片不能简单按像素逐个“续写”",
      "扩散模型的直观过程",
      "文字怎样控制画面",
      "为什么在潜在空间工作",
      "为什么相同提示会生成不同图片",
      "视频为什么更难",
      "多模态模型怎样连接不同信息",
      "生成图片的四层核验",
      "小活动：固定提示，只改变一个变量",
      "本课小结",
      "参考资料",
    ),
    Content: MultimodalGeneration,
  },
  {
    ...common,
    slug: "agents-world-models-embodied-ai",
    chapterLabel: "大模型如何工作 · 第 7 课",
    title: "Agent、世界模型与具身智能",
    description: "从生成回答走向执行任务，理解 Agent、世界模型、具身智能、工具权限与物理安全边界。",
    readingTime: "预计学习 24—30 分钟",
    sections: markdownSections(
      "本课目标",
      "一次回答与一个任务不是同一件事",
      "Agent 的六个组成部分",
      "工具结果也可能错",
      "权限设计：默认最小，关键步骤确认",
      "世界模型：预测“行动以后会发生什么”",
      "具身智能不是“给聊天机器人装身体”",
      "为什么物理世界需要更硬的边界",
      "学生怎样负责任地使用 Agent",
      "设计练习：校园节水 Agent",
      "本课小结",
      "参考资料",
    ),
    Content: AgentsWorldModelsAndEmbodiedAi,
  },
  {
    ...common,
    slug: "hallucination-bias-and-safety",
    chapterLabel: "大模型如何工作 · 第 8 课",
    title: "幻觉、偏差、资源与安全边界",
    description: "认识幻觉、偏差、隐私、版权、资源消耗和行动权限，建立分层核验与责任意识。",
    readingTime: "预计学习 26—32 分钟",
    sections: markdownSections(
      "本课目标",
      "“幻觉”不是模型看见了不存在的东西",
      "一套四层核验法",
      "偏差不只来自“有偏见的句子”",
      "隐私：不要把对话框当成私人草稿纸",
      "版权与创作责任",
      "能源和资源：讨论要有边界",
      "行动权限：从“说错”升级为“做错”",
      "大模型输出检查清单",
      "情景题",
      "本课小结",
      "参考资料",
    ),
    Content: HallucinationBiasAndSafety,
  },
  {
    ...common,
    slug: "hands-on-challenges",
    chapterLabel: "大模型如何工作 · 第 9 课",
    title: "动手实验与章节挑战",
    description: "通过活动观察 Token、概率、注意力、工具调用与事实核验，并制作自己的大模型说明卡。",
    readingTime: "预计实践 50—80 分钟",
    sections: markdownSections(
      "活动说明",
      "活动一：比较不同分词方法",
      "活动二：自己当下一 Token 预测器",
      "活动三：用 Transformer Explainer 看模型内部",
      "活动四：做一次幻觉核验",
      "活动五：比较“模型回答”与“使用工具的回答”",
      "活动六：拆解一个 Agent 任务",
      "活动七：把“大”变成可以感受的数量",
      "章节挑战：制作一张“大模型说明卡”",
      "章节测验",
      "给家长和教师的话",
    ),
    Content: LargeModelChallenges,
  },
  {
    ...common,
    slug: "glossary-and-resources",
    chapterLabel: "大模型如何工作 · 资料页",
    title: "术语表、发展脉络与参考资料",
    description: "集中复习大模型核心术语、发展脉络、代表性资料与章节结束检查问题。",
    readingTime: "按需查阅",
    sections: markdownSections(
      "核心术语速查",
      "一条简化的发展脉络",
      "大语言模型与 Transformer",
      "发展历史与训练方法",
      "图片、视频与多模态",
      "Agent、机器人与风险治理",
      "用八个问题结束这一章",
    ),
    Content: LargeModelGlossary,
  },
];
