import MachineLearningIntroduction from "../../../docs/markdown/机器学习与深度学习/00-章节导读.md";
import RulesToMachineLearning from "../../../docs/markdown/机器学习与深度学习/01-从规则到机器学习.md";
import DataFeaturesAndLearning from "../../../docs/markdown/机器学习与深度学习/02-数据特征标签与学习方式.md";
import NeuralNetworkComputation from "../../../docs/markdown/机器学习与深度学习/03-神经网络如何计算.md";
import LearningFromErrors from "../../../docs/markdown/机器学习与深度学习/04-模型如何从错误中学习.md";
import DeepRepresentationLearning from "../../../docs/markdown/机器学习与深度学习/05-深度与表示学习.md";
import NeuralNetworkArchitectures from "../../../docs/markdown/机器学习与深度学习/06-典型神经网络架构.md";
import GeneralizationAndEvaluation from "../../../docs/markdown/机器学习与深度学习/07-泛化偏差与可靠评估.md";
import MachineLearningChallenges from "../../../docs/markdown/机器学习与深度学习/08-动手实验与章节挑战.md";
import MachineLearningGlossary from "../../../docs/markdown/机器学习与深度学习/09-术语表与参考资料.md";
import { markdownSections, type LessonEntry } from "./course-types";

const common = {
  chapter: "machine-learning",
  contentKind: "markdown" as const,
  audience: "建议年龄 10—14 岁",
};

export const machineLearningLessons: LessonEntry[] = [
  {
    ...common,
    slug: "introduction",
    chapterLabel: "机器学习与深度学习 · 章节导读",
    title: "机器学习与深度学习：章节导读",
    description: "从生活中的识别与预测出发，建立机器学习、深度学习、数据、训练和可靠评估的完整学习路线。",
    readingTime: "预计学习 10—12 分钟",
    sections: markdownSections(
      "这一章要解决什么问题",
      "适合谁学习",
      "学习路线",
      "学完后的能力目标",
      "阅读时请带着这五个问题",
      "开始前的小挑战",
      "原始资料说明",
    ),
    Content: MachineLearningIntroduction,
  },
  {
    ...common,
    slug: "rules-to-machine-learning",
    chapterLabel: "机器学习与深度学习 · 第 1 课",
    title: "从规则到机器学习",
    description: "比较固定规则与从数据学习，判断什么任务适合使用机器学习，并理清 AI、机器学习与深度学习的关系。",
    readingTime: "预计学习 20—25 分钟",
    sections: markdownSections(
      "本课目标",
      "普通程序从明确规则出发",
      "有些规则很难写完",
      "机器学习不是“把答案存进去”",
      "AI、机器学习和深度学习的关系",
      "什么问题适合机器学习",
      "常见误区",
      "检查理解",
      "本课小结",
      "参考资料",
    ),
    Content: RulesToMachineLearning,
  },
  {
    ...common,
    slug: "data-features-labels",
    chapterLabel: "机器学习与深度学习 · 第 2 课",
    title: "数据、特征、标签与学习方式",
    description: "认识样本、特征、标签和数据集等核心概念，理解监督、无监督和强化学习的反馈方式。",
    readingTime: "预计学习 25—30 分钟",
    sections: markdownSections(
      "本课目标",
      "六个必须先分清的词",
      "一条可靠的数据链",
      "三种常见学习方式",
      "数据最容易在哪些地方“骗过”我们",
      "小练习：设计一个校园垃圾分类模型",
      "检查理解",
      "本课小结",
      "参考资料",
    ),
    Content: DataFeaturesAndLearning,
  },
  {
    ...common,
    slug: "neural-network-computation",
    chapterLabel: "机器学习与深度学习 · 第 3 课",
    title: "神经网络如何计算",
    description: "从函数、神经元、权重和激活函数出发，理解多层神经网络如何把输入转换为预测。",
    readingTime: "预计学习 20—25 分钟",
    sections: markdownSections(
      "本课目标",
      "先从函数开始",
      "一个神经元做了两件事",
      "为什么必须有非线性",
      "从一个神经元到一张网络",
      "一个小例子：判断是否适合户外运动",
      "参数多意味着什么",
      "纸上实验：自己当一个神经元",
      "常见误区",
      "本课小结",
      "参考资料",
    ),
    Content: NeuralNetworkComputation,
  },
  {
    ...common,
    slug: "learning-from-errors",
    chapterLabel: "机器学习与深度学习 · 第 4 课",
    title: "模型如何从错误中学习",
    description: "跟随前向传播、损失、反向传播和梯度下降，观察模型怎样利用错误更新参数。",
    readingTime: "预计学习 25—30 分钟",
    sections: markdownSections(
      "本课目标",
      "训练不是“多看几遍数据”这么简单",
      "第一步：前向传播",
      "第二步：损失函数把错误变成数值",
      "第三步：反向传播追踪每个参数的影响",
      "第四步：优化器更新参数",
      "批次、轮次与随机性",
      "训练集损失下降，为什么还不能庆祝",
      "动手推演：一步更新发生了什么",
      "常见误区",
      "检查理解",
      "本课小结",
      "参考资料",
    ),
    Content: LearningFromErrors,
  },
  {
    ...common,
    slug: "deep-representation-learning",
    chapterLabel: "机器学习与深度学习 · 第 5 课",
    title: "深度与表示学习",
    description: "理解深度、特征工程、表示学习、端到端学习与迁移学习之间的关系。",
    readingTime: "预计学习 18—22 分钟",
    sections: markdownSections(
      "本课目标",
      "“深”首先是计算结构，不是思想深刻",
      "传统特征工程：先把经验写进输入",
      "表示学习：让模型学习“什么信息值得保留”",
      "端到端学习意味着什么",
      "深度学习为什么特别适合非结构化数据",
      "迁移学习：已经学到的表示可以再利用",
      "思考活动：信息在哪一层变得有用",
      "常见误区",
      "本课小结",
      "参考资料",
    ),
    Content: DeepRepresentationLearning,
  },
  {
    ...common,
    slug: "neural-network-architectures",
    chapterLabel: "机器学习与深度学习 · 第 6 课",
    title: "从 MLP 到 Transformer",
    description: "比较 MLP、CNN、RNN、LSTM、ResNet 与 Transformer 的信息连接方式和适用场景。",
    readingTime: "预计学习 28—35 分钟",
    sections: markdownSections(
      "本课目标",
      "架构是在回答“信息应该怎样连接”",
      "感知机：能从例子调整边界的早期判断器",
      "MLP：通用的全连接组合器",
      "CNN：在图片上复用局部观察窗口",
      "RNN 与 LSTM：让历史状态随序列传递",
      "ResNet：给深层网络增加“捷径”",
      "Transformer：让不同位置按需要相互参考",
      "不是直线淘汰，而是组合工具箱",
      "为什么这些旧想法在近十多年迎来爆发",
      "架构侦探练习",
      "本课小结",
      "参考资料",
    ),
    Content: NeuralNetworkArchitectures,
  },
  {
    ...common,
    slug: "generalization-and-evaluation",
    chapterLabel: "机器学习与深度学习 · 第 7 课",
    title: "泛化、偏差与可靠评估",
    description: "学习数据划分、过拟合、数据泄漏、评估指标与分布变化，建立可靠评估意识。",
    readingTime: "预计学习 24—30 分钟",
    sections: markdownSections(
      "本课目标",
      "模型价值要在没见过的数据上体现",
      "三类数据各自负责什么",
      "数据怎样划分才不会泄漏",
      "准确率之外还要看什么",
      "总体成绩可能掩盖群体差异",
      "分布变化：现实不会永远停在训练那天",
      "对抗“捷径学习”",
      "可靠性检查清单",
      "检查理解",
      "本课小结",
      "参考资料",
    ),
    Content: GeneralizationAndEvaluation,
  },
  {
    ...common,
    slug: "hands-on-challenges",
    chapterLabel: "机器学习与深度学习 · 第 8 课",
    title: "动手实验与章节挑战",
    description: "通过免编程实验观察训练、决策边界、过拟合与模型审计，完成可信机器学习项目设计。",
    readingTime: "预计实践 40—60 分钟",
    sections: markdownSections(
      "实验目标",
      "实验一：用 Teachable Machine 训练手势分类器",
      "实验二：在 TensorFlow Playground 观察决策边界",
      "实验三：纸上模型审计",
      "实验四：没有网络也能做的“纸牌学习器”",
      "章节挑战：设计一个可信的小型机器学习项目",
      "章节测验",
      "给家长和教师的话",
      "项目评价量规",
    ),
    Content: MachineLearningChallenges,
  },
  {
    ...common,
    slug: "glossary-and-resources",
    chapterLabel: "机器学习与深度学习 · 资料页",
    title: "术语表与参考资料",
    description: "集中复习机器学习核心术语、常见误区、推荐学习顺序与代表性架构资料。",
    readingTime: "按需查阅",
    sections: markdownSections(
      "核心术语速查",
      "九个常见说法，哪些需要修正",
      "推荐学习顺序",
      "代表性架构论文",
      "用五个问题结束这一章",
    ),
    Content: MachineLearningGlossary,
  },
];
